### ISSUE TITLE
A store app token is required and has not been included during client creation

### ISSUE THREAD

**Issue by zhuwendong** [univapay/univapay-php-sdk#44]
![微信图片_20230906102212](https://github.com/univapay/univapay-php-sdk/assets/21135301/ca82d2ec-0a07-42b4-844a-a9e55d9ee866)
![微信图片_20230906102223](https://github.com/univapay/univapay-php-sdk/assets/21135301/5e3a2c58-c20b-4afa-bb32-3967f64232a1)
prompt A store app token is required and has not been included during client creation，What is the reason for this

**Comment by kgston** [comment]
It is very likely you might have created a `merchant app token` instead of a `store app token`. Information about the differences is explain on [this page](https://docs.univapay.com/en/app-tokens/#application_token_types). 

In addition, please be careful about sharing your app token secret on the internet in your screenshots. For security, I recommend deactivating that specific app token now that the secret has been exposed.

**Comment by kgston** [comment]
I will delete the first image off your post due to the secret being exposed on it.

**Comment by zhuwendong** [comment]
![1695368665952](https://github.com/univapay/univapay-php-sdk/assets/21135301/98c7c7fc-a9f7-477f-a89e-31183dc2bcd8)
![1695368724482](https://github.com/univapay/univapay-php-sdk/assets/21135301/1042aec6-06af-4038-9b97-29711226046c)
What is this mistake
