### ISSUE TITLE
【Q&A】Check webhook status.

### ISSUE THREAD

**Issue by huylong** [univapay/univapay-php-sdk#54]
Sorry for setting up this Q&A.
Can you please tell me how to check webhook information setup status via API?
Is there any way to check if its status is Active?
Currently I can only check on the management screen https://merchant-console.gopay.jp.

**Comment by kgston** [comment]
Currently we have not implemented the webhook management API on the PHP SDK.
You can implement it manually according to the documentation [here](https://docs.univapay.com/en/References/webhooks-get/).

However, do note that we _do not recommend_ programmatically reactivating your webhooks if you find them getting automatically disabled due to your application being unable to handle the influx of webhooks during heavy processing. It would be best to address the performance issues of your webhook endpoint before reactivating the webhook from the console.

Our recommended approach to ensuring your webhook endpoint do not fail is to create a separate app/microservice for receiving webhooks and then storing them into a DB table or message queue to be subsequently/asyncronously processed by your main application. That would ensure your webhook endpoint service will not fail and is able to respond with the correct HTTP status to us, preventing your webhook from being automatically disabled. Attempting to execute changes when receiving webhooks is not a very scalable solution.

**Comment by huylong** [comment]
I got it.
Thank you very much.
